### ISSUE TITLE
Mautic 2.0 critical errors after updating from 1.4.1

### ISSUE THREAD

**Issue by jimsimjim** [mautic/mautic#1988]
## Description

Updated to 2.0 through command line using the recommended upgrade.php - https://raw.githubusercontent.com/mautic/mautic/master/upgrade.php as mentioned here - https://www.mautic.org/community/index.php/4823-2-0-0-released.

Using 5.6 and the required system requirements

**Now have the following errors in log amongst others of similar type**

-  mautic.CRITICAL: Uncaught PHP Exception BadMethodCallException: "Undefined method 'getDwellTimesForUrls'. The method name must start with either findBy or findOneBy! vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php line 226 {"exception":"[object] (BadMethodCallException(code: 0):
-  mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE INDEX ef_email_date_read ON ef_email_stats (date_read)':  SQLSTATE[42000]: Syntax error or access violation: 
-  mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'UPDATE ef_leads SET attribution_date = ? WHERE id = ?' with params [null, 10408]:  SQLSTATE[42S22]:
- mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE INDEX ef_event_type ON ef_campaign_events (event_type)':  SQLSTATE[42000]: Syntax error or access violation: 
- [2016-07-07 21:36:45] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'UPDATE ef_leads SET country = ?, attribution_date = ? WHERE id = ?' ... :  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribution_date' in 'field list'" at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'UPDATE ef_leads SET country = ?, attribution_date = ? WHERE id = ?' with params [\"country\", null, 29359]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribution_date' in 'field list' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribution_date' in 'field list' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribution_date' in 'field list' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Also it is not possible to press apply when amending contacts**

**Contacts sometimes 500 errors**

## Steps to reproduce

Upgrade to 2.0 
Edit contacts and try and press apply
Go through contact list page by page and see if 500 error occurs

Edit contact

**Comment by escopecz** [comment]
Some of the errors above are already fixed and will be released in 2.0.1 soon. Some are caused by missing column in the database. To fix those, follow http://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful.

**Comment by jimsimjim** [comment]
Hello, I actually tried the recommendations in the blog post before posting here and it didnt work and still had the above errors

**Comment by tleyva** [comment]
when I do the `php app/console doctrine:schema:update --force`
i get this error:
`There is no column with name 'attribution' on table 'leads'.
Updating database schema...
There is no column with name 'attribution' on table 'leads'.                                                                                                                                                                                                               

  [Doctrine\DBAL\Exception\DriverException]                                                                                                                                                                    
  An exception occurred while executing 'CREATE INDEX greetings_search ON leads (greetings)':                                                                                                                  
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'greetings' used in key s                                                                                                           pecification without a key length
                                                                                                                 
  [Doctrine\DBAL\Driver\PDOException]                                                                                                                                                                          
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'greetings' used in key s                                                                                                           pecification without a key length

  [PDOException]                                                                                                                                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'greetings' used in key s                                                                                                           pecification without a key length`

**Comment by escopecz** [comment]
These SQL issues when running the schema:update command are fixed in Mautic 2.1.0
