### ISSUE TITLE
Export a segment

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1865]
Be able to export the leads from a segment to send over to sales.

**Comment by npracht** [comment]
You already have an CSV export button on top right of contact list displayed.
Isn't enough? Otherwise please describe a bit more your need.

**Comment by ldrrp** [comment]
i dont see what you are referencing. I dont see an export button.

**Comment by ldrrp** [comment]
Non of these buttons are labeled for export, Mostly batch edit. Am i in the right place.

![image](https://cloud.githubusercontent.com/assets/985837/16453871/68b39db2-3ddc-11e6-82ed-66cbc86f093e.png)

**Comment by npracht** [comment]
Hello @Idrrp,

Which version of mautic do you have ?
Cause i have -->
![capture d ecran 2016-07-12 a 10 43 12](https://cloud.githubusercontent.com/assets/14075239/16760735/7ec7a7b0-481d-11e6-84fb-d17ea04c6d45.png)

**Comment by ldrrp** [comment]
I always run on the latest stable release, 2.0.0 right now

**Comment by ldrrp** [comment]
Not sure if related but my logs are below. I keep getting that in the log. it doesn't seem related


`
[2016-07-12 14:05:58] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /var/www/html/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-12 14:05:58] mautic.CRITICAL: Uncaught PHP Exception BadMethodCallException: "Undefined method 'getDwellTimesForUrls'. The method name must start with either findBy or findOneBy!" at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php line 226 {"exception":"[object] (BadMethodCallException(code: 0): Undefined method 'getDwellTimesForUrls'. The method name must start with either findBy or findOneBy! at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:226)"} []

`

**Comment by npracht** [comment]
Hi @ldrrp i just noticed that **we forgot to pull request this feature** to the community.
It'll come as far as we'll have updated our work on the 2.0.0 version.

Sorry for the misunderstanding.

N.

**Comment by npracht** [comment]
Then it's a duplicate of https://github.com/mautic/mautic/issues/597

**Comment by patmifsud** [comment]
Hey npracht  and ldrrp, conversation is a little over my head here, i'm just wondering if you could give a laymans summary on what this means for self hosted mautic users and when we can expect to see the csv export feature? So happy to see it exists somewhere. Thanks!!!

**Comment by ldrrp** [comment]
Seems it wasnt added to the code. It should be in soon @patmifsud

**Comment by patmifsud** [comment]
Thanks Idrrp, David!

**Comment by MaxWebmecanik** [comment]
I'm working on pushing this feature back to the community #2165

**Comment by angelsguitar** [comment]
I missed this feature was going to be included on the 2.2.0 release. An easy way to export contact's from a certain segment would be handy. Any news on this?

**Comment by wheresmylunch** [comment]
Is this now up? Running 2.2 and cant see this where you are suggesting.

**Comment by npracht** [comment]
Hi @wheresmylunch it is not. The PR is there https://github.com/mautic/mautic/pull/2165 but mautic team asked us to refactor the way we propose it. We didn't have time to work on it yes unfortunately.
Don't hesitate to carry the modifications requested if you think you can do it and want it faster.

N.

**Comment by patmifsud** [comment]
Can this be reopened? I'm not familiar with how Github works but it seems as though this hasn't been resolved.

**Comment by escopecz** [comment]
This might solve this issue by searching for the contacts in a segment and hit export: https://github.com/mautic/mautic/pull/3123

**Comment by ldrrp** [comment]
this is working on the latest release. you can close.
