### ISSUE TITLE
Uncaught TypeError: Mautic.getActiveBuilderName is not a function

### ISSUE THREAD

**Issue by ebogaard** [mautic/mautic#10735]
### Mautic Version

4.0.0

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

After upgrading from 3.3.x to 4.1.1 using the CLI, all links in Mautic stopped working. If you click any link on the page, you can see the loading bar activatig, but then nothing happens.
This goes for the links on the dashboard, the links in the menu on the left and the settings menu on the right.
If I right click + open in new tab, most links work and I get to see the page I expect in the new tab.
This still leaves about 20% of the links not working.

I did a file-by-file diff and only some files in app/config, themes and some Tests are different/missing.
I've cleared the cache many times before each retry.

### How can we reproduce this issue?

Step 1: Install Mautic 3.3.x
Step 2: Upgrade via the CLI to 4.1.1
Step 3L Log-in and cliack any link

### Relevant log output

```shell
There's no error logs in the php or the httpd log. In the browser console, the following javascript error is shown:

app.js:92:11
Uncaught TypeError: Mautic.getActiveBuilderName is not a function
    onPageUnload https://example.com/media/js/app.js?v65d68e90:92
    processPageContent https://example.com/media/js/app.js?v65d68e90:55
    success https://example.com/media/js/app.js?v65d68e90:43
    fire https://example.com/media/js/libraries.js?v65d68e90:344
    fireWith https://example.com/media/js/libraries.js?v65d68e90:350
    done https://example.com/media/js/libraries.js?v65d68e90:752
    callback https://example.com/media/js/libraries.js?v65d68e90:765
    send https://example.com/media/js/libraries.js?v65d68e90:765
    ajax https://example.com/media/js/libraries.js?v65d68e90:744
    loadContent https://example.com/media/js/app.js?v65d68e90:40
    ajaxifyLink https://example.com/media/js/app.js?v65d68e90:108
    makeLinksAlive https://example.com/media/js/app.js?v65d68e90:91
    dispatch https://example.com/media/js/libraries.js?v65d68e90:465
    handle https://example.com/media/js/libraries.js?v65d68e90:451
    add https://example.com/media/js/libraries.js?v65d68e90:453
    on https://example.com/media/js/libraries.js?v65d68e90:445
    each https://example.com/media/js/libraries.js?v65d68e90:153
    each https://example.com/media/js/libraries.js?v65d68e90:144
    on https://example.com/media/js/libraries.js?v65d68e90:445
    on https://example.com/media/js/libraries.js?v65d68e90:481
    makeLinksAlive https://example.com/media/js/app.js?v65d68e90:91
    onPageLoad https://example.com/media/js/app.js?v65d68e90:64
    <anonymous> https://example.com/s/dashboard:556
```
```


### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
hi @ebogaard can you please update to 4.1.2 and see if this issue persists? 

Also maybe you might need to clear out your browser cache? Sometimes that causes issues with the JS between releases. Please try to delete your browser cache and/or check in an incognito window.

If neither of those resolve the issue, please try regenerating the production assets using the command 

`bin/console mautic:assets:generate`

**Comment by ebogaard** [comment]
Sorry for the delay.
I've just tested the upgrade from 3.3 to 4.1.2 and again have the same issue.

Cleared the browser cache, did a hard refresh and used a incognito window: makes no difference.

Tried bin/console mautic:assets:generate, then again cleared cache, etc: no difference.
Tried another browser, in which I haven't used Mautic before: no difference.

UPDATE:
After some debugging: I can get things working, if I put the following code
```
echo '<script>Mautic.getActiveBuilderName = function() { return \'legacy\'; }</script>'."\n";
```
Outside the "if":
```
if ($this->installService->checkIfInstalled()) {
```
This is in "app/bundles/CoreBundle/Templating/Helper/AssetsHelper.php", around line 470 in function "outputSystemScripts".

So it seems "$this->installService->checkIfInstalled()"  returns false for some reason.

Further digging shows that "$params['db_driver']" is empty.
This is because we programmatically set this parameter in "app/config/parameters_local.php".
If I add this parameter to "app/config/local.php", Mautic works without the change in "app/bundles/CoreBundle/Templating/Helper/AssetsHelper.php".

So the original issue turns into another issue: why aren't the parameters in "parameters_local.php" added to the "$params" array in "app/bundles/InstallBundle/Install/InstallService.php", as they are picked up by Mautic in other places presumably, because the DB configuration (and other parameters) we set in that file are used by Mautic.
