### ISSUE TITLE
Email builder Drag`n Drop not working

### ISSUE THREAD

**Issue by AlanRezende** [mautic/mautic#3417]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I can`t  drag and drop things on email builder

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 5.6.26

### Steps to reproduce:
1. Enter the email builder
2. Try to drag a button on text to email area
 
### Log errors: 

On chrome console when I enter the builder it throws the error:
``Uncaught TypeError: Cannot read property 'document' of null``
``at HTMLDivElement.helper (http://domain/folderwithmautic/media/js/app.js?vefa80e05:169:339)
``

When I try to drag the components a lot of errors like the one bellow are thrown
``Uncaught TypeError: Cannot read property 'document' of null``
``at HTMLDivElement.helper (http://domain/folderwithmautic/media/js/app.js?vefa80e05:169:339)``

**Comment by escopecz** [comment]
Actually, I'm getting the missing `mauticLang` variable error which is fixed by this PR: https://github.com/mautic/mautic/pull/3422 I cannot replicate the error you posted. Does it happen with some theme only? Or some browser only?

**Comment by luizeof** [comment]
@escopecz @AlanRezende tested on Safari, Chrome and Opera ... same issue.

On Blank theme I found this error from javascript console after drag some elements:

TypeError: Mautic.updateDynamicContentDropdown is not a function
 /app/bundles/CoreBundle/Assets/js/libraries/froala/plugins/dynamic_content.js

Looks like we have some minor bug with Z-index when drag some elements to email body

![download](https://cloud.githubusercontent.com/assets/257004/22906462/aca32d54-f22b-11e6-983e-a11296f598ef.png)

**Comment by thomeudt** [comment]
Facing a similar issue after migrating to 2.6:

Drag/Drop works when creating a new e-mail, but after having saved and re-opening, I can no longer access any text blocks (images still work) for editing.

Tested with Chrome and Safari.

Console shows the following errors:

`Uncaught ReferenceError: mauticLang is not defined
    at Object.translate (app.js?v32a5bf02:10)
    at app.js?v32a5bf02:302
translate @ app.js?v32a5bf02:10
(anonymous) @ app.js?v32a5bf02:302
dynamic_content.js?v32a5bf02:57 Uncaught TypeError: Mautic.updateDynamicContentDropdown is not a function
    at Object._init (dynamic_content.js?v32a5bf02:57)
    at FE.load (froala_editor.js?v32a5bf02:260)
    at FE.<anonymous> (froala_editor.js?v32a5bf02:109)
    at HTMLImageElement.proxy (libraries.js?v32a5bf02:156)
    at HTMLImageElement.dispatch (libraries.js?v32a5bf02:404)
    at HTMLImageElement.elemData.handle (libraries.js?v32a5bf02:379)
    at Object.trigger (libraries.js?v32a5bf02:399)
    at HTMLImageElement.<anonymous> (libraries.js?v32a5bf02:437)
    at Function.each (libraries.js?v32a5bf02:149)
    at jQuery.fn.init.each (libraries.js?v32a5bf02:139)`
